version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db:/var/lib/mysql

  node:
    image: node:18-alpine
    container_name: node
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
